### ISSUE TITLE
While connecting to solr , I am getting  java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by girishvn31** [jcustenborder/kafka-connect-solr#2]
I am trying to send data to solr from kafka but getting errors as mentioned below.

[2017-03-29 11:03:16,989] INFO HttpSolrSinkConnectorConfig values:
	solr.commit.within = -1
	solr.core.name = girish1
	solr.ignore.unknown.fields = false
	solr.password = [hidden]
	solr.url = http://192.168.1.5:8983/solr/
	solr.username =
 (com.github.jcustenborder.kafka.connect.solr.HttpSolrSinkConnectorConfig:180)
[2017-03-29 11:03:16,990] INFO Creating Solr client. (com.github.jcustenborder.kafka.connect.solr.SolrSinkTask:48)
[2017-03-29 11:03:17,348] ERROR Task girishsolr-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:142)
java.lang.IllegalArgumentException
	at java.util.concurrent.LinkedBlockingQueue.<init>(LinkedBlockingQueue.java:261)
	at org.apache.solr.client.solrj.impl.ConcurrentUpdateSolrClient.<init>(ConcurrentUpdateSolrClient.java:146)
	at org.apache.solr.client.solrj.impl.ConcurrentUpdateSolrClient$Builder.build(ConcurrentUpdateSolrClient.java:684)
	at com.github.jcustenborder.kafka.connect.solr.HttpSolrSinkTask.client(HttpSolrSinkTask.java:39)
	at com.github.jcustenborder.kafka.connect.solr.SolrSinkTask.start(SolrSinkTask.java:49)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:221)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-03-29 11:03:17,352] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:143)
[2017-03-29 11:03:17,352] ERROR Task girishsolr-0 threw an uncaught and unrecoverable exception during shutdown (org.apache.kafka.connect.runtime.WorkerTask:123)
java.lang.NullPointerException
	at com.github.jcustenborder.kafka.connect.solr.SolrSinkTask.stop(SolrSinkTask.java:86)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.close(WorkerSinkTask.java:127)
	at org.apache.kafka.connect.runtime.WorkerTask.doClose(WorkerTask.java:121)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-03-29 11:03:26,485] INFO Reflections took 11541 ms to scan 279 urls, producing 12476 keys and 82021 values  (org.reflections.Reflections:229)

Environment Details - 
Confluent Version - 3.1.0
Solr Version - 6.3.0
Java Version - openjdk version "1.8.0_111"

command - connect-standalone $CONFLUENT_HOME/etc/schema-registry/connect-avro-standalone.properties /opt/confluent/connectors/kafka-connect-solr/config/httpsolr.properties

$CONFLUENT_HOME - /opt/confluent/confluent-3.1.0

**Comment by jcustenborder** [comment]
@girishvn31 Can you take a look at this branch [config-issue](https://github.com/jcustenborder/kafka-connect-solr/tree/config-issue)?

**Comment by jcustenborder** [comment]
Can you try the latest version? This should be resolved?
