### ISSUE TITLE
SOLRj 7.3.0 and UpdateRequest.setCommitWithin error

### ISSUE THREAD

**Issue by ramyogi** [jcustenborder/kafka-connect-solr#32]
Thanks a lot for this awesome plugin. It is so great.

Hi ,
As per https://www.confluent.io/hub/jcustenborder/kafka-connect-solr
I have installed 
jcustenborder/kafka-connect-solr:0.1.33
After that replaced solrsolr-solrj-8.2.0.jar by solr-solrj-7.3.0.jar and added one more jar noggit-0.8.jar,

With below config creator connector but received below exception:
{
  
    "connector.class" : "com.github.jcustenborder.kafka.connect.solr.CloudSolrSinkConnector",
    "tasks.max" : "1",
    "topics" : "test",
    "solr.zookeeper.hosts" : "test.zk:2181",
    "transforms" : "dropPrefix",
    "transforms.dropPrefix.type" : "org.apache.kafka.connect.transforms.RegexRouter",
    "transforms.dropPrefix.regex" : ".*",
    "transforms.dropPrefix.replacement" : "test_collection",
    "solr.commit.within" : "1"
}

java.lang.NoSuchMethodError: org.apache.solr.client.solrj.request.UpdateRequest.setCommitWithin(I)Lorg/apache/solr/client/solrj/request/AbstractUpdateRequest;
	at com.github.jcustenborder.kafka.connect.solr.Operations.addOperation(Operations.java:45)
	at com.github.jcustenborder.kafka.connect.solr.Operations.delete(Operations.java:72

**Comment by ramyogi** [comment]
I even tried replaced only solrsolr-solrj-8.2.0.jar by solr-solrj-7.5.0.jar 
Still I get the same error. We are using server solr version is 7.5.0. 
Any suggestion to resolve this ?

**Comment by ramyogi** [comment]
If I do not place noggit-*.jar, I am getting  for the solrj version 7.5.0
Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
java.lang.NoClassDefFoundError: org/noggit/JSONWriter$Writable
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:96)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.solr.client.solrj.impl.CloudSolrClient$Builder.build(CloudSolrClient.java:1582)
	at com.github.jcustenborder.kafka.connect.solr.CloudSolrSinkTask.start(CloudSolrSinkTask.java:46)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:300)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:189)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.noggit.JSONWriter$Writable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 22 more

**Comment by jcustenborder** [comment]
@ramyogi In order to get things to work you must have all of the dependencies. Try changing the [version](https://github.com/jcustenborder/kafka-connect-solr/blob/master/pom.xml#L54) to `7.5.0` and run `mvn clean package` notice *package*. That's the important one. You're just copying the jar file which doesn't have the dependencies. look in `target/kafka-connect-target/` All of the files you need will be in this folder.

**Comment by ramyogi** [comment]
Thanks jcustenborder. Question:
For kafka-connect elastic search below is applicable do we have the same for solr sink connector as well ?

Sending a malformed JSON to kafka topic results in connector task failing by default.

By setting the connector task config property behavior.on.malformed.documents to either warn or ignore, the error json message is sent to dead letter queue set by the property errors.deadletterqueue.topic.name

**Comment by jcustenborder** [comment]
`errors.deadletterqueue.topic.name` is something at the Kafka Connect level so it will work with any connector.
