### ISSUE TITLE
ZK connection time out config variable ?

### ISSUE THREAD

**Issue by ramyogi** [jcustenborder/kafka-connect-solr#33]
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.solr.common.SolrException: java.util.concurrent.TimeoutException: Could not connect to ZooKeeper zookeeper.cert.scopussearch.net:2181/author within 15000 ms
	at org.apache.solr.common.cloud.SolrZkClient.<init>(SolrZkClient.java:201)
	at org.apache.solr.common.cloud.SolrZkClient.<init>(SolrZkClient.java:125)
	at org.apache.solr.common.cloud.SolrZkClient.<init>(SolrZkClient.java:115)
	at org.apache.solr.common.cloud.ZkStateReader.<init>(ZkStateReader.java:355)
	at org.apache.solr.client.solrj.impl.ZkClientClusterStateProvider.getZkStateReader(ZkClientClusterStateProvider.java:175)
	at org.apache.solr.client.solrj.impl.ZkClientClusterStateProvider.connect(ZkClientClusterStateProvider.java:160)
	at org.apache.solr.client.solrj.impl.BaseCloudSolrClient.connect(BaseCloudSolrClient.java:331)
	at org.apache.solr.client.solrj.impl.BaseCloudSolrClient.requestWithRetryOnStaleState(BaseCloudSolrClient.java:839)
	at org.apache.solr.client.solrj.impl.BaseCloudSolrClient.request(BaseCloudSolrClient.java:829)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:211)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:228)
	at com.github.jcustenborder.kafka.connect.solr.CloudSolrSinkTask.process(CloudSolrSinkTask.java:53)
	at com.github.jcustenborder.kafka.connect.solr.SolrSinkTask.put(SolrSinkTask.java:75)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:538)
	... 10 more
Caused by: java.util.concurrent.TimeoutException: Could not connect to ZooKeeper test.zookeeper.com/test within 15000 ms
	at org.apache.solr.common.cloud.ConnectionManager.waitForConnected(ConnectionManager.java:250)
	at org.apache.solr.common.cloud.SolrZkClient.<init>(SolrZkClient.java:192)

**Comment by ramyogi** [comment]
is there a way to pass ZK connection time value to increase

**Comment by jcustenborder** [comment]
@ramyogi I added the configuration parameters [solr.zookeeper.connect.timeout.ms](https://jcustenborder.github.io/kafka-connect-documentation/projects/kafka-connect-solr/sinks/CloudSolrSinkConnector.html#solr-zookeeper-connect-timeout-ms), [solr.zookeeper.client.timeout.ms](https://jcustenborder.github.io/kafka-connect-documentation/projects/kafka-connect-solr/sinks/CloudSolrSinkConnector.html#solr-zookeeper-client-timeout-ms), and [solr.zookeeper.retry.expiry.time.ms](https://jcustenborder.github.io/kafka-connect-documentation/projects/kafka-connect-solr/sinks/CloudSolrSinkConnector.html#solr-zookeeper-retry-expiry-time-ms) for you. The default is a really high timeout for zookeeper so there might be something else wrong in the environment. Give this a shot and let me know how it goes. It's available in [0.1.34](https://www.confluent.io/hub/jcustenborder/kafka-connect-solr)

**Comment by ramyogi** [comment]
Thanks a lot.
